# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env_files:
  github_token: ~/.keys/github_token
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows # We use $HOME for some default paths atm...
      - darwin
    ldflags:
    - "-X cmd.version={{ .Tag }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
release:
  github:
    owner: fvumbaca
    name: journal
  prerelease: auto
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
